zotcard-card-report = - Card Report

zotcard-card-report-cards = Card count
zotcard-card-report-none = <None>

zotcard-card-report-today = Today is { $date }, the week of { $weekOfYear }.
zotcard-card-report-build = This report is generated by zotcard at { $create }
zotcard-card-report-since = Since { $first } ({ $fromDays } days ago) I first wrote the card:

zotcard-card-report-total = Cumulative card count
zotcard-card-report-words = Cumulative word count
zotcard-card-report-avg_words = Average word count per calorie
zotcard-card-report-content_scale = Total content proportion
zotcard-card-report-days = Cumulative card writing days
zotcard-card-report-days_scale = Number of days to write cards
zotcard-card-report-avg_cards = Write cards every day on average
zotcard-card-report-sizes = Take up space

zotcard-card-report-last = Last write card at { $last },
zotcard-card-report-nonCard = Meaning? You haven't written your card in { $day } days.
zotcard-card-report-todayCard = Great. You wrote the card today.
zotcard-card-report-advancedCard = Huh? You wrote the card { $day } days in advance.

zotcard-card-report-cardtypes = Card sorting summary
zotcard-card-report-cardtags = Card label summary
zotcard-card-report-specialcard = Special card
zotcard-card-report-specialcard-date1 = First card
zotcard-card-report-specialcard-date2 = Last card
zotcard-card-report-specialcard-date-content = , created in { $date }.
zotcard-card-report-specialcard-words1 = Least word card
zotcard-card-report-specialcard-words2 = Card with the most words
zotcard-card-report-specialcard-words-content = , { $words } word.
zotcard-card-report-specialcard-lines1 = The card with the fewest lines
zotcard-card-report-specialcard-lines2 = The card with the most lines
zotcard-card-report-specialcard-lines-content = , { $lines } lines.
zotcard-card-report-specialcard-sizes1 = The card that takes up the least space
zotcard-card-report-specialcard-sizes2 = The card that takes up the most space
zotcard-card-report-specialcard-sizes-content = , takes up space { $sizes }.
zotcard-card-report-specialcard-content_scales1 = The card with the smallest Content Scales
zotcard-card-report-specialcard-content_scales2 = The card with the largest Content Scales
zotcard-card-report-specialcard-content_scales-content = The Content Scales is { $content_scales }%.

zotcard-card-report-weeks = Weekly summary
zotcard-card-report-months = Monthly summary
zotcard-card-report-years = Annual summary

zotcard-card-report-years-detail = { $year } A total of { $days } days to write cards, accounting for the entire year of { $days_scale }%, cumulative { $words } words, { $total } cards.
