(function() {
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-l10ns.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-l10ns.js");
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-messages.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-messages.js");
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-datetimes.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-datetimes.js");
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-prefs.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-prefs.js");
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-notes.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-notes.js");
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-cards.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-cards.js");
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-doms.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-doms.js");
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-events.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-events.js");
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-items.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-items.js");
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-collections.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-collections.js");
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-readers.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-readers.js");
    Services.scriptloader.loadSubScript(rootURI + '/chrome/content/modules/zotcard-utils.js');
    Zotero.ZotCard.Logger.log("loadSubScript zotcard-utils.js");
})();